In [ ]:
import os
import re
import pandas as pd
import numpy as np
from pathlib import Path
import warnings

warnings.filterwarnings("ignore")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DATASET_PATH = "/content/drive/MyDrive/Internship project/dataset"

In [ ]:
persons = sorted([
    folder for folder in os.listdir(DATASET_PATH)
    if os.path.isdir(os.path.join(DATASET_PATH, folder))
])

print(f"Total Personas : {len(persons)}")

for person in persons:
    print(person)

Total Personas : 11
ARAVIND MENON
Abdul Rahman chats
Abhijith +2
Alan techie
Arjun Toyota
Maria Nurse
Priya Nair chats
ROHAN MENON
Suresh Auto
adithya chats
farzan chats

In [ ]:
MESSAGE_PATTERN = re.compile(
    r"^(\d{2}/\d{2}/\d{2},\s\d{1,2}:\d{2}\s(?:AM|PM))\s-\s([^:]+):\s?(.*)"
)

In [ ]:
SYSTEM_EVENTS = [

    "<Media omitted>",
    "<Photo omitted>",
    "<Video omitted>",
    "<Sticker omitted>",
    "<GIF omitted>",
    "<Document omitted>",

    "Voice call",
    "Video call",
    "Missed voice call",
    "Missed video call",

    "Live location shared",
    "Location shared",

    "This message was deleted",
    "You deleted this message"
]

In [ ]:
SEPARATOR_PATTERN = re.compile(r"^[─—-]{5,}$")

In [ ]:
def parse_whatsapp_chat(file_path, person, chat_name):

    messages = []

    with open(file_path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()

    current_message = None

    for line in lines:

        line = line.strip()

        # ---------------------------------------
        # Skip empty lines
        # ---------------------------------------
        if line == "":
            continue

        # ---------------------------------------
        # Skip separators
        # ---------------------------------------
        if SEPARATOR_PATTERN.match(line):
            continue

        # ---------------------------------------
        # Check for new WhatsApp message
        # ---------------------------------------
        match = MESSAGE_PATTERN.match(line)

        if match:

            # Save previous message
            if current_message is not None:
                messages.append(current_message)

            timestamp = match.group(1)
            sender = match.group(2).strip()
            message = match.group(3).strip()

            current_message = {
                "Person": person,
                "Chat_Name": chat_name,
                "Timestamp": timestamp,
                "Sender": sender,
                "Message": message
            }

        else:

            # Continuation of previous message
            if current_message is not None:

                current_message["Message"] += "\n" + line

    # Save last message
    if current_message is not None:
        messages.append(current_message)

    return messages

In [ ]:
all_messages = []

for person in persons:

    person_folder = os.path.join(DATASET_PATH, person)

    txt_files = sorted(Path(person_folder).glob("*.txt"))

    print(f"{person} : {len(txt_files)} chats")

    for txt_file in txt_files:

        chat_name = txt_file.stem

        parsed = parse_whatsapp_chat(
            txt_file,
            person,
            chat_name
        )

        all_messages.extend(parsed)

ARAVIND MENON : 22 chats
Abdul Rahman chats : 22 chats
Abhijith +2 : 40 chats
Alan techie : 29 chats
Arjun Toyota : 47 chats
Maria Nurse : 40 chats
Priya Nair chats : 21 chats
ROHAN MENON : 17 chats
Suresh Auto : 34 chats
adithya chats : 37 chats
farzan chats : 29 chats

In [ ]:
df = pd.DataFrame(all_messages)

print(df.shape)

df.head()

(19936, 5)

,Person,Chat_Name,Timestamp,Sender,Message
0,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 07:00 AM",Coach Manoj,"\nMorning! New year, new goals right? What are..."
1,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:30 AM",You,\nHonestly just consistency. Roster makes it h...
2,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:32 AM",Coach Manoj,\nFair enough. Let's do a flexible split then ...
3,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:35 AM",You,\nThat works. When can we start?
4,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:36 AM",Coach Manoj,\nTomorrow morning if you're free. 6 AM slot o...

In [ ]:
print(df.isnull().sum())

Person       0
Chat_Name    0
Timestamp    0
Sender       0
Message      0
dtype: int64

In [ ]:
print("Empty Messages:", (df["Message"] == "").sum())

Empty Messages: 0

In [ ]:
df[df["Message"].str.contains("────", na=False)]

Empty DataFrame
Columns: [Person, Chat_Name, Timestamp, Sender, Message]
Index: []

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 104

In [ ]:
df.sample(10, random_state=42)

,Person,Chat_Name,Timestamp,Sender,Message
803,ARAVIND MENON,Chat with Meera S,"18/02/26, 09:30 PM",Meera,\n📸 <Screenshot omitted>
1350,Abdul Rahman chats,Basheer,"27/01/26, 09:05 PM",Basheer,\nഈ നമ്പർ സേവ് ചെയ്യണ്ട.
322,ARAVIND MENON,Chat with Aparna,"19/03/26, 09:06 PM",You,\n📷 <Media omitted>
17486,adithya chats,Chat with chechi,"15/02/26, 07:44 PM",Chechi 👩,"Candle, flowers, chocolate... safe combo 😂"
10963,Priya Nair chats,class teacher,"27/03/26, 12:52 PM",Priya,\nThank you so much miss.\nWe will continue pr...
16559,adithya chats,Chat with Kutty ❤️,"29/05/26, 11:26 AM",Kutty ❤️,Fridayyy 😌
10826,Priya Nair chats,Husband,"30/06/26, 01:22 PM",Arun Ettan 🇦🇪,\nSalary kittumbo ayakkam ❤️
10008,Priya Nair chats,Husband,"04/03/26, 06:36 PM",Priya,\n📷 <Media omitted>\nEvening walk 😄
13320,adithya chats,Auto chettan,"09/01/26, 08:27 AM",Auto Chettan 🚖,\nPurath ethi.
8174,Maria Nurse,chat with athira,"28/04/26, 07:45 PM",You,\nAa.\n6:15 bus pidikkanam.

In [ ]:
duplicates = df[
    df.duplicated(
        subset=["Person","Chat_Name","Timestamp","Sender","Message"],
        keep=False
    )
].sort_values(
    ["Person","Chat_Name","Timestamp"]
)

duplicates

,Person,Chat_Name,Timestamp,Sender,Message
2772,Abhijith +2,football boys,"09/04/26, 08:12 PM",Arun,\nGuys\nSunday 6:30 AM okay?
2777,Abhijith +2,football boys,"09/04/26, 08:12 PM",Arun,\nGuys\nSunday 6:30 AM okay?
2773,Abhijith +2,football boys,"09/04/26, 08:13 PM",Nikhil,\nOkay
2778,Abhijith +2,football boys,"09/04/26, 08:13 PM",Nikhil,\nOkay
2774,Abhijith +2,football boys,"09/04/26, 08:14 PM",You,\nNjan varam
...,...,...,...,...,...
13192,Suresh Auto,chat with wife,"06/03/26, 07:12 PM",Meera ❤️,Toy shopil ninn gift eduthalo?
13179,Suresh Auto,chat with wife,"06/03/26, 07:19 PM",You,Aa... pillerk ishtam aavunna enthelum nokkam.
13193,Suresh Auto,chat with wife,"06/03/26, 07:19 PM",You,Aa... pillerk ishtam aavunna enthelum nokkam.
13180,Suresh Auto,chat with wife,"06/03/26, 07:20 PM",Meera ❤️,👍
13194,Suresh Auto,chat with wife,"06/03/26, 07:20 PM",Meera ❤️,👍

In [ ]:
print(len(duplicates))

208

In [ ]:
duplicates.head(20)

,Person,Chat_Name,Timestamp,Sender,Message
2772,Abhijith +2,football boys,"09/04/26, 08:12 PM",Arun,\nGuys\nSunday 6:30 AM okay?
2777,Abhijith +2,football boys,"09/04/26, 08:12 PM",Arun,\nGuys\nSunday 6:30 AM okay?
2773,Abhijith +2,football boys,"09/04/26, 08:13 PM",Nikhil,\nOkay
2778,Abhijith +2,football boys,"09/04/26, 08:13 PM",Nikhil,\nOkay
2774,Abhijith +2,football boys,"09/04/26, 08:14 PM",You,\nNjan varam
2779,Abhijith +2,football boys,"09/04/26, 08:14 PM",You,\nNjan varam
2775,Abhijith +2,football boys,"09/04/26, 08:15 PM",Rahul,\nLate aavaruth 😂
2780,Abhijith +2,football boys,"09/04/26, 08:15 PM",Rahul,\nLate aavaruth 😂
2776,Abhijith +2,football boys,"09/04/26, 08:16 PM",You,\n😂
2781,Abhijith +2,football boys,"09/04/26, 08:16 PM",You,\n😂
4923,Alan techie,chat with aron cousin,"01/03/26, 08:58 PM",Aaron 🇬🇧,"Eda, enthokke vishesham?"
4945,Alan techie,chat with aron cousin,"01/03/26, 08:58 PM",Aaron 🇬🇧,"Eda, enthokke vishesham?"
4924,Alan techie,chat with aron cousin,"01/03/26, 09:00 PM",You,Onnum illa. Same routine 😄
4946,Alan techie,chat with aron cousin,"01/03/26, 09:00 PM",You,Onnum illa. Same routine 😄
4925,Alan techie,chat with aron cousin,"01/03/26, 09:01 PM",Aaron 🇬🇧,😂 Ath thanne.
4947,Alan techie,chat with aron cousin,"01/03/26, 09:01 PM",Aaron 🇬🇧,😂 Ath thanne.
4926,Alan techie,chat with aron cousin,"01/03/26, 09:02 PM",Aaron 🇬🇧,Veettil poyirunno ee week?
4948,Alan techie,chat with aron cousin,"01/03/26, 09:02 PM",Aaron 🇬🇧,Veettil poyirunno ee week?
4927,Alan techie,chat with aron cousin,"01/03/26, 09:03 PM",You,Illa. Next week povum.
4949,Alan techie,chat with aron cousin,"01/03/26, 09:03 PM",You,Illa. Next week povum.

In [ ]:
print(df.shape)

(19936, 5)

In [ ]:
duplicates[
    ["Person", "Chat_Name", "Timestamp", "Sender", "Message"]
].to_string()

'             Person                            Chat_Name           Timestamp     Sender                                                                 Message\n2772    Abhijith +2                        football boys  09/04/26, 08:12 PM       Arun                                            \\nGuys\\nSunday 6:30 AM okay?\n2777    Abhijith +2                        football boys  09/04/26, 08:12 PM       Arun                                            \\nGuys\\nSunday 6:30 AM okay?\n2773    Abhijith +2                        football boys  09/04/26, 08:13 PM     Nikhil                                                                  \\nOkay\n2778    Abhijith +2                        football boys  09/04/26, 08:13 PM     Nikhil                                                                  \\nOkay\n2774    Abhijith +2                        football boys  09/04/26, 08:14 PM        You                                                            \\nNjan varam\n2779    Abhijith +2                        football boys  09/04/26, 08:14 PM        You                                                            \\nNjan varam\n2775    Abhijith +2                        football boys  09/04/26, 08:15 PM      Rahul                                                       \\nLate aavaruth 😂\n2780    Abhijith +2                        football boys  09/04/26, 08:15 PM      Rahul                                                       \\nLate aavaruth 😂\n2776    Abhijith +2                        football boys  09/04/26, 08:16 PM        You                                                                     \\n😂\n2781    Abhijith +2                        football boys  09/04/26, 08:16 PM        You                                                                     \\n😂\n4923    Alan techie                chat with aron cousin  01/03/26, 08:58 PM   Aaron 🇬🇧                                                Eda, enthokke vishesham?\n4945    Alan techie                chat with aron cousin  01/03/26, 08:58 PM   Aaron 🇬🇧                                                Eda, enthokke vishesham?\n4924    Alan techie                chat with aron cousin  01/03/26, 09:00 PM        You                                              Onnum illa. Same routine 😄\n4946    Alan techie                chat with aron cousin  01/03/26, 09:00 PM        You                                              Onnum illa. Same routine 😄\n4925    Alan techie                chat with aron cousin  01/03/26, 09:01 PM   Aaron 🇬🇧                                                           😂 Ath thanne.\n4947    Alan techie                chat with aron cousin  01/03/26, 09:01 PM   Aaron 🇬🇧                                                           😂 Ath thanne.\n4926    Alan techie                chat with aron cousin  01/03/26, 09:02 PM   Aaron 🇬🇧                                              Veettil poyirunno ee week?\n4948    Alan techie                chat with aron cousin  01/03/26, 09:02 PM   Aaron 🇬🇧                                              Veettil poyirunno ee week?\n4927    Alan techie                chat with aron cousin  01/03/26, 09:03 PM        You                                                  Illa. Next week povum.\n4949    Alan techie                chat with aron cousin  01/03/26, 09:03 PM        You                                                  Illa. Next week povum.\n4928    Alan techie                chat with aron cousin  01/03/26, 09:04 PM   Aaron 🇬🇧                                                    Ammayod hi parayane.\n4950    Alan techie                chat with aron cousin  01/03/26, 09:04 PM   Aaron 🇬🇧                                                    Ammayod hi parayane.\n4937    Alan techie                chat with aron cousin  11/04/26, 09:21 PM   Aaron 🇬🇧                                                   Easterinu leave undo?\n4959    Alan techie                chat with aron cousin  11/04/26, 09:21 PM   Aaron 🇬🇧                                                   Easterinu leave undo?\n4938    Alan techie                chat with aron cousin  11/04/26, 09:22 PM        You                                                     Und. Naattil povum.\n4960    Alan techie                chat with aron cousin  11/04/26, 09:22 PM        You                                                     Und. Naattil povum.\n4939    Alan techie                chat with aron cousin  11/04/26, 09:23 PM   Aaron 🇬🇧                                         Super. Enikku leave kitiyilla 🥲\n4961    Alan techie                chat with aron cousin  11/04/26, 09:23 PM   Aaron 🇬🇧                                         Super. Enikku leave kitiyilla 🥲\n4940    Alan techie                chat with aron cousin  11/04/26, 09:24 PM        You                                      Saaramilla. Next year set aakkam 😊\n4962    Alan techie                chat with aron cousin  11/04/26, 09:24 PM        You                                      Saaramilla. Next year set aakkam 😊\n4929    Alan techie                chat with aron cousin  16/03/26, 10:12 PM   Aaron 🇬🇧                                     Video call cheyyan pattumo weekend?\n4951    Alan techie                chat with aron cousin  16/03/26, 10:12 PM   Aaron 🇬🇧                                     Video call cheyyan pattumo weekend?\n4930    Alan techie                chat with aron cousin  16/03/26, 10:13 PM        You                                         Pattum. Sunday evening mathiyo?\n4952    Alan techie                chat with aron cousin  16/03/26, 10:13 PM        You                                         Pattum. Sunday evening mathiyo?\n4931    Alan techie                chat with aron cousin  16/03/26, 10:14 PM   Aaron 🇬🇧                                                               Perfect 👍\n4953    Alan techie                chat with aron cousin  16/03/26, 10:14 PM   Aaron 🇬🇧                                                               Perfect 👍\n4941    Alan techie                chat with aron cousin  25/04/26, 08:44 PM   Aaron 🇬🇧                                                            Alive ano? 😑\n4963    Alan techie                chat with aron cousin  25/04/26, 08:44 PM   Aaron 🇬🇧                                                            Alive ano? 😑\n4942    Alan techie                chat with aron cousin  25/04/26, 08:45 PM        You                                                       😂 Busy aayirunnu.\n4964    Alan techie                chat with aron cousin  25/04/26, 08:45 PM        You                                                       😂 Busy aayirunnu.\n4943    Alan techie                chat with aron cousin  25/04/26, 08:46 PM   Aaron 🇬🇧                                      Busy allelum oru "hi" ayakkamallo.\n4965    Alan techie                chat with aron cousin  25/04/26, 08:46 PM   Aaron 🇬🇧                                      Busy allelum oru "hi" ayakkamallo.\n4944    Alan techie                chat with aron cousin  25/04/26, 08:47 PM        You                                                        Sheri chetta 😂❤️\n4966    Alan techie                chat with aron cousin  25/04/26, 08:47 PM        You                                                        Sheri chetta 😂❤️\n4932    Alan techie                chat with aron cousin  29/03/26, 07:36 PM   Aaron 🇬🇧                                                       📷 <Media omitted>\n4954    Alan techie                chat with aron cousin  29/03/26, 07:36 PM   Aaron 🇬🇧                                                       📷 <Media omitted>\n4933    Alan techie                chat with aron cousin  29/03/26, 07:37 PM   Aaron 🇬🇧                                                       Innathe weather 😒\n4955    Alan techie                chat with aron cousin  29/03/26, 07:37 PM   Aaron 🇬🇧                                                       Innathe weather 😒\n4934    Alan techie                chat with aron cousin  29/03/26, 07:38 PM        You                                                             Mazha aano?\n4956    Alan techie                chat with aron cousin  29/03/26, 07:38 PM        You                                                             Mazha aano?\n4935    Alan techie                chat with aron cousin  29/03/26, 07:39 PM   Aaron 🇬🇧                                                          Aah. Full day.\n4957    Alan techie                chat with aron cousin  29/03/26, 07:39 PM   Aaron 🇬🇧                                                          Aah. Full day.\n4936    Alan techie                chat with aron cousin  29/03/26, 07:40 PM        You                                                     Ivide nalla chood 😂\n4958    Alan techie                chat with aron cousin  29/03/26, 07:40 PM        You                                                     Ivide nalla chood 😂\n5911   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:44 PM     Anjali                 \\nEtta,\\nVacation confirm aayi.\\nMay 14 class kazhiyum.\n5929   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:44 PM     Anjali                 \\nEtta,\\nVacation confirm aayi.\\nMay 14 class kazhiyum.\n5912   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:45 PM        You                                                      \\nAppo eppo varum?\n5930   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:45 PM        You                                                      \\nAppo eppo varum?\n5913   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:46 PM     Anjali                                      \\n15th ravile train aanu nokkunne.\n5931   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:46 PM     Anjali                                      \\n15th ravile train aanu nokkunne.\n5914   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:47 PM        You                                             \\nOk.\\nTicket eduthittundo?\n5932   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:47 PM        You                                             \\nOk.\\nTicket eduthittundo?\n5915   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:48 PM     Anjali                                                      \\nIlla.\\nNokkanam.\n5933   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:48 PM     Anjali                                                      \\nIlla.\\nNokkanam.\n5916   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:49 PM        You                                                   \\nNjanum nokkam.\\n---\n5934   Arjun Toyota                 chat with Anjali Sis  05/05/26, 08:49 PM        You                                                   \\nNjanum nokkam.\\n---\n5917   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:16 PM     Anjali                        \\nEtta,\\nVacation varumbo enthelum kondu varano?\n5935   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:16 PM     Anjali                        \\nEtta,\\nVacation varumbo enthelum kondu varano?\n5918   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:17 PM        You                                  \\nVenda.\\nNee safe aayi vannal mathi 😄\n5936   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:17 PM        You                                  \\nVenda.\\nNee safe aayi vannal mathi 😄\n5919   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:18 PM     Anjali                                   \\nAmma paranju achar vangikond varan.\n5937   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:18 PM     Anjali                                   \\nAmma paranju achar vangikond varan.\n5920   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:19 PM        You                                              \\nAthokke Amma nokkikolum.\n5938   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:19 PM        You                                              \\nAthokke Amma nokkikolum.\n5921   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:20 PM     Anjali                                                                \\n😂\\n---\n5939   Arjun Toyota                 chat with Anjali Sis  12/05/26, 09:20 PM     Anjali                                                                \\n😂\\n---\n5922   Arjun Toyota                 chat with Anjali Sis  16/05/26, 07:24 PM     Anjali           \\nEtta,\\nBus stand ethi.\\n07/24 PM - You:\\nAchan vannittundo?\n5940   Arjun Toyota                 chat with Anjali Sis  16/05/26, 07:24 PM     Anjali           \\nEtta,\\nBus stand ethi.\\n07/24 PM - You:\\nAchan vannittundo?\n5923   Arjun Toyota                 chat with Anjali Sis  16/05/26, 07:25 PM     Anjali                                              \\nAa.\\nVeettil ethum ippo.\n5941   Arjun Toyota                 chat with Anjali Sis  16/05/26, 07:25 PM     Anjali                                              \\nAa.\\nVeettil ethum ippo.\n5924   Arjun Toyota                 chat with Anjali Sis  16/05/26, 07:26 PM        You                                                              \\nOk.\\n---\n5942   Arjun Toyota                 chat with Anjali Sis  16/05/26, 07:26 PM        You                                                              \\nOk.\\n---\n5925   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:52 PM     Anjali                \\nEtta,\\nNext semester August-il thudangum ennu paranju.\n5943   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:52 PM     Anjali                \\nEtta,\\nNext semester August-il thudangum ennu paranju.\n5926   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:53 PM        You                                     \\nAppo kurach days veettil undallo.\n5944   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:53 PM        You                                     \\nAppo kurach days veettil undallo.\n5927   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:54 PM     Anjali                                                                  \\nAa 😄\n5945   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:54 PM     Anjali                                                                  \\nAa 😄\n5928   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:55 PM        You                                  \\nEnjoy cheyyu.\\nPinne padikkanum und.\n5946   Arjun Toyota                 chat with Anjali Sis  29/05/26, 08:55 PM        You                                  \\nEnjoy cheyyu.\\nPinne padikkanum und.\n6384   Arjun Toyota                      chat with nihal  11/04/26, 07:46 PM      Nihal                                                     \\nDa,\\nSugham alle?\n6404   Arjun Toyota                      chat with nihal  11/04/26, 07:46 PM      Nihal                                                     \\nDa,\\nSugham alle?\n6385   Arjun Toyota                      chat with nihal  11/04/26, 07:47 PM        You                                               \\nSugham da.\\nNee engane?\n6405   Arjun Toyota                      chat with nihal  11/04/26, 07:47 PM        You                                               \\nSugham da.\\nNee engane?\n6386   Arjun Toyota                      chat with nihal  11/04/26, 07:48 PM      Nihal                                \\nNannayi pokunnu.\\nWork okke busy aanu.\n6406   Arjun Toyota                      chat with nihal  11/04/26, 07:48 PM      Nihal                                \\nNannayi pokunnu.\\nWork okke busy aanu.\n6387   Arjun Toyota                      chat with nihal  11/04/26, 07:49 PM        You                                                      \\nIppo evide aanu?\n6407   Arjun Toyota                      chat with nihal  11/04/26, 07:49 PM        You                                                      \\nIppo evide aanu?\n6388   Arjun Toyota                      chat with nihal  11/04/26, 07:50 PM      Nihal                                \\nKochi side aanu.\\nOru company-il aanu.\n6408   Arjun Toyota                      chat with nihal  11/04/26, 07:50 PM      Nihal                                \\nKochi side aanu.\\nOru company-il aanu.\n6389   Arjun Toyota                      chat with nihal  11/04/26, 07:51 PM        You                                                              \\nNannayi.\n6409   Arjun Toyota                      chat with nihal  11/04/26, 07:51 PM        You                                                              \\nNannayi.\n6390   Arjun Toyota                      chat with nihal  11/04/26, 07:52 PM      Nihal                                         \\nNinte Toyota work engane und?\n6410   Arjun Toyota                      chat with nihal  11/04/26, 07:52 PM      Nihal                                         \\nNinte Toyota work engane und?\n6391   Arjun Toyota                      chat with nihal  11/04/26, 07:53 PM        You                               \\nOk aanu.\\nRush undenkilum padikkunnund.\n6411   Arjun Toyota                      chat with nihal  11/04/26, 07:53 PM        You                               \\nOk aanu.\\nRush undenkilum padikkunnund.\n6392   Arjun Toyota                      chat with nihal  11/04/26, 07:54 PM      Nihal                                 \\nAth nannayi.\\nExperience kittum.\\n---\n6412   Arjun Toyota                      chat with nihal  11/04/26, 07:54 PM      Nihal                                 \\nAth nannayi.\\nExperience kittum.\\n---\n6393   Arjun Toyota                      chat with nihal  22/04/26, 08:16 PM      Nihal                                               \\nDa,\\nWeekend free aano?\n6413   Arjun Toyota                      chat with nihal  22/04/26, 08:16 PM      Nihal                                               \\nDa,\\nWeekend free aano?\n6394   Arjun Toyota                      chat with nihal  22/04/26, 08:17 PM        You                                    \\nSaturday work und.\\nSunday nokkam.\n6414   Arjun Toyota                      chat with nihal  22/04/26, 08:17 PM        You                                    \\nSaturday work und.\\nSunday nokkam.\n6395   Arjun Toyota                      chat with nihal  22/04/26, 08:18 PM      Nihal                               \\nOk.\\nNammal kure naal aayi kandittilla.\n6415   Arjun Toyota                      chat with nihal  22/04/26, 08:18 PM      Nihal                               \\nOk.\\nNammal kure naal aayi kandittilla.\n6396   Arjun Toyota                      chat with nihal  22/04/26, 08:19 PM        You                              \\nAa.\\nDiploma kazhinju ellarum busy aayi.\n6416   Arjun Toyota                      chat with nihal  22/04/26, 08:19 PM        You                              \\nAa.\\nDiploma kazhinju ellarum busy aayi.\n6397   Arjun Toyota                      chat with nihal  22/04/26, 08:20 PM      Nihal                                \\nSheriya.\\nLife motham work aayi poyi 😂\n6417   Arjun Toyota                      chat with nihal  22/04/26, 08:20 PM      Nihal                                \\nSheriya.\\nLife motham work aayi poyi 😂\n6398   Arjun Toyota                      chat with nihal  22/04/26, 08:21 PM        You                                                     \\nAth thanne 😂\\n---\n6418   Arjun Toyota                      chat with nihal  22/04/26, 08:21 PM        You                                                     \\nAth thanne 😂\\n---\n8730    Maria Nurse                 chat with sister law  03/01/26, 08:42 PM  Chechi ❤️                                                    \\nHappy New Year 😊❤️\n8784    Maria Nurse                 chat with sister law  03/01/26, 08:42 PM  Chechi ❤️                                                    \\nHappy New Year 😊❤️\n8731    Maria Nurse                 chat with sister law  03

In [ ]:
system_events = df[
    df["Sender"].str.contains(
        "Voice|Video|Missed|Messages and calls",
        case=False,
        na=False
    )
]

print(system_events.shape)

system_events.head(20)

(0, 5)

Empty DataFrame
Columns: [Person, Chat_Name, Timestamp, Sender, Message]
Index: []

In [ ]:
print("Before:", len(df))

df = df.drop_duplicates(
    subset=[
        "Person",
        "Chat_Name",
        "Timestamp",
        "Sender",
        "Message"
    ],
    keep="first"
).reset_index(drop=True)

print("After:", len(df))

Before: 19936
After: 19832

In [ ]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/Internship project/master_whatsapp_dataset.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!