In [ ]:
import pandas as pd
import numpy as np
import re

import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv(
    "/content/drive/MyDrive/Internship project/master_whatsapp_dataset.csv"
)

print(df.shape)

df.head()

(19832, 5)

,Person,Chat_Name,Timestamp,Sender,Message
0,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 07:00 AM",Coach Manoj,"\nMorning! New year, new goals right? What are..."
1,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:30 AM",You,\nHonestly just consistency. Roster makes it h...
2,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:32 AM",Coach Manoj,\nFair enough. Let's do a flexible split then ...
3,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:35 AM",You,\nThat works. When can we start?
4,ARAVIND MENON,Chat wiith Coach Manoj,"04/01/26, 08:36 AM",Coach Manoj,\nTomorrow morning if you're free. 6 AM slot o...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19832 entries, 0 to 19831
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Person     19832 non-null  object
 1   Chat_Name  19832 non-null  object
 2   Timestamp  19832 non-null  object
 3   Sender     19832 non-null  object
 4   Message    19832 non-null  object
dtypes: object(5)
memory usage: 774.8+ KB

In [ ]:
df.isnull().sum()

Person       0
Chat_Name    0
Timestamp    0
Sender       0
Message      0
dtype: int64

In [ ]:
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    format="%d/%m/%y, %I:%M %p"
)

ValueError: day is out of range for month, at position 7838. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
temp = pd.to_datetime(
    df["Timestamp"],
    format="%d/%m/%y, %I:%M %p",
    errors="coerce"
)

bad_rows = df[temp.isna()]

print("Invalid timestamps:", len(bad_rows))
bad_rows[["Person", "Chat_Name", "Timestamp"]]

Invalid timestamps: 7

            Person             Chat_Name           Timestamp
7838   Maria Nurse  chat with ancy nurse  29/02/26, 08:58 PM
7839   Maria Nurse  chat with ancy nurse  29/02/26, 08:59 PM
7840   Maria Nurse  chat with ancy nurse  29/02/26, 09:04 PM
7841   Maria Nurse  chat with ancy nurse  29/02/26, 09:05 PM
7842   Maria Nurse  chat with ancy nurse  29/02/26, 09:06 PM
7843   Maria Nurse  chat with ancy nurse  29/02/26, 09:07 PM
12750  Suresh Auto   chat with babu auto  06/21/26, 06:31 PM

In [ ]:
df["Timestamp_Original"] = df["Timestamp"]

In [ ]:
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    format="%d/%m/%y, %I:%M %p",
    errors="coerce"
)

In [ ]:
df = df.dropna(subset=["Timestamp"])

In [ ]:
print("Invalid timestamps:", df["Timestamp"].isna().sum())

Invalid timestamps: 0

In [ ]:
# Validate timestamps first
temp = pd.to_datetime(
    df["Timestamp"],
    format="%d/%m/%y, %I:%M %p",
    errors="coerce"
)

invalid = df[temp.isna()]

print(f"Invalid timestamps: {len(invalid)}")

if len(invalid) > 0:
    display(invalid[["Person", "Chat_Name", "Timestamp"]])
    raise ValueError("Fix the invalid timestamps before continuing.")

# Safe conversion
df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    format="%d/%m/%y, %I:%M %p"
)

Invalid timestamps: 0

In [ ]:
df["Date"] = df["Timestamp"].dt.date

df["Time"] = df["Timestamp"].dt.time

df["Year"] = df["Timestamp"].dt.year

df["Month"] = df["Timestamp"].dt.month

df["Month_Name"] = df["Timestamp"].dt.month_name()

df["Day"] = df["Timestamp"].dt.day

df["Weekday"] = df["Timestamp"].dt.day_name()

df["Hour"] = df["Timestamp"].dt.hour

df["Minute"] = df["Timestamp"].dt.minute

In [ ]:
df["Message"] = (
    df["Message"]
    .astype(str)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [ ]:
df["Is_Media"] = (
    df["Message"]
    .str.contains("media omitted", case=False, na=False)
)

In [ ]:
df["Is_Location"] = (
    df["Message"]
    .str.contains("location", case=False, na=False)
)

In [ ]:
df["Is_Deleted"] = (
    df["Message"]
    .str.contains("deleted", case=False, na=False)
)

In [ ]:
df["Is_Call"] = (
    df["Message"]
    .str.contains("call", case=False, na=False)
)

In [ ]:
df["Is_URL"] = (
    df["Message"]
    .str.contains(r"http|www", case=False, regex=True)
)

In [ ]:
df["Character_Count"] = df["Message"].str.len()

df["Word_Count"] = (
    df["Message"]
    .str.split()
    .str.len()
)

In [ ]:
df["Is_Weekend"] = df["Weekday"].isin([
    "Saturday",
    "Sunday"
])

In [ ]:
df["Is_Night"] = (
    (df["Hour"] >= 22) |
    (df["Hour"] <= 5)
)

In [ ]:
print(df.shape)

df.head()

(19825, 24)

,Person,Chat_Name,Timestamp,Sender,Message,Timestamp_Original,Date,Time,Year,Month,...,Minute,Is_Media,Is_Location,Is_Deleted,Is_Call,Is_URL,Character_Count,Word_Count,Is_Weekend,Is_Night
0,ARAVIND MENON,Chat wiith Coach Manoj,2026-01-04 07:00:00,Coach Manoj,"Morning! New year, new goals right? What are w...","04/01/26, 07:00 AM",2026-01-04,07:00:00,2026,1,...,0,False,False,False,False,False,132,22,True,False
1,ARAVIND MENON,Chat wiith Coach Manoj,2026-01-04 08:30:00,You,Honestly just consistency. Roster makes it har...,"04/01/26, 08:30 AM",2026-01-04,08:30:00,2026,1,...,30,False,False,False,False,False,116,20,True,False
2,ARAVIND MENON,Chat wiith Coach Manoj,2026-01-04 08:32:00,Coach Manoj,Fair enough. Let's do a flexible split then — ...,"04/01/26, 08:32 AM",2026-01-04,08:32:00,2026,1,...,32,False,False,False,False,False,155,30,True,False
3,ARAVIND MENON,Chat wiith Coach Manoj,2026-01-04 08:35:00,You,That works. When can we start?,"04/01/26, 08:35 AM",2026-01-04,08:35:00,2026,1,...,35,False,False,False,False,False,30,6,True,False
4,ARAVIND MENON,Chat wiith Coach Manoj,2026-01-04 08:36:00,Coach Manoj,Tomorrow morning if you're free. 6 AM slot open.,"04/01/26, 08:36 AM",2026-01-04,08:36:00,2026,1,...,36,False,False,False,False,False,48,9,True,False

In [ ]:
df.isnull().sum()

Person                0
Chat_Name             0
Timestamp             0
Sender                0
Message               0
Timestamp_Original    0
Date                  0
Time                  0
Year                  0
Month                 0
Month_Name            0
Day                   0
Weekday               0
Hour                  0
Minute                0
Is_Media              0
Is_Location           0
Is_Deleted            0
Is_Call               0
Is_URL                0
Character_Count       0
Word_Count            0
Is_Weekend            0
Is_Night              0
dtype: int64

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/Internship project/preprocessed_whatsapp_dataset.csv",
    index=False
)

print("Preprocessed dataset saved successfully!")

Preprocessed dataset saved successfully!